"""create users table

Revision ID: f7bd28bc4246
Revises: 
Create Date: 2026-07-22 19:27:59.837956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7bd28bc4246'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('forma_pago', sa.String(length=20), nullable=False))

    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('inventario', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.drop_column('inventario')

    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.drop_column('forma_pago')

    # ### end Alembic commands ###
